In [2]:
# Load the Pandas libraries with alias 'pd' 
import pandas as pd 
# Read data from file 'filename.csv' 
# (in the same directory that your python process is based)
# Control delimiters, rows, column names with read_csv (see later) 
data = pd.read_csv("C:\Users\dbsxsl\Desktop\Food_consumption_2008_2018_countries.csv") 
# Preview the first 5 lines of the loaded data 
data.head()

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-2-49f6c507cc2c>, line 6)

In [2]:
# Load the Pandas libraries with alias 'pd' 
import pandas as pd 
# Read data from file 'filename.csv' 
# (in the same directory that your python process is based)
# Control delimiters, rows, column names with read_csv (see later) 
data = pd.read_csv(r"C:\Users\dbsxsl\Desktop\Food_consumption_2008_2018_countries.csv") 
# Preview the first 5 lines of the loaded data 
data.head()

,Country,Year,FoodCode,FoodName,AgeClass,SourceAgeClass,Gender,Number_of_consumers,Consumers_Mean,Consumers_Median,...,Consumers_Standard_deviation__g_day_,Number_of_subjects,Total_Mean,Total_Median,Total_P05__g_day_,Total_P90__g_day_,Total_P95__g_day_,Total_P975__g_day_,Total_Standard_deviation__g_day_,Intake_Unit
0,United States of America,2010,298638831e59722a35d3c6f2d76d9366,NaN,All,All,All,24289,2.615611,1.979999,...,2.059695,24673,2.574902,1.952711,0.495401,5.358520,6.802777,8.186428,2.069091,g/kg.bw/day
1,United States of America,2010,298638831e59722a35d3c6f2d76d9366,NaN,Infants and Toddlers,0-35 months,male,1184,4.768847,4.434707,...,3.041306,1379,4.094500,3.813671,0.000000,8.544207,9.939184,11.088991,3.271661,g/kg.bw/day
2,United States of America,2010,298638831e59722a35d3c6f2d76d9366,NaN,Children and Adolescents,3-5 years,male,732,5.700705,5.493517,...,2.388509,734,5.685172,5.480028,2.286188,8.783987,10.075738,10.963900,2.403714,g/kg.bw/day
3,United States of America,2010,298638831e59722a35d3c6f2d76d9366,NaN,Children and Adolescents,6-14 years,male,2154,3.624891,3.274886,...,1.944444,2155,3.623209,3.272666,1.082396,6.222071,7.320617,8.310850,1.945560,g/kg.bw/day
4,United States of America,2010,298638831e59722a35d3c6f2d76d9366,NaN,Adults and Elderly,15-49 years,male,4414,2.370472,2.044994,...,1.538174,4415,2.369935,2.044759,0.650260,4.181051,5.212911,6.310622,1.538413,g/kg.bw/day

In [3]:
# data1 = oringal data dataframe without NaN value  
data1 = data.dropna() 
data1.head()

,Country,Year,FoodCode,FoodName,AgeClass,SourceAgeClass,Gender,Number_of_consumers,Consumers_Mean,Consumers_Median,...,Consumers_Standard_deviation__g_day_,Number_of_subjects,Total_Mean,Total_Median,Total_P05__g_day_,Total_P90__g_day_,Total_P95__g_day_,Total_P975__g_day_,Total_Standard_deviation__g_day_,Intake_Unit
21,United States of America,2010,A000M,Amaranth grains,All,All,All,16,0.002277,0.001429,...,0.005255,24673,1.430000e-06,0.0,0.0,0.0,0.0,0.0,0.000144,g/kg.bw/day
22,United States of America,2010,A000M,Amaranth grains,Infants and Toddlers,0-35 months,male,0,0.000000,0.000000,...,0.000000,1379,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000,g/kg.bw/day
23,United States of America,2010,A000M,Amaranth grains,Children and Adolescents,3-5 years,male,0,0.000000,0.000000,...,0.000000,734,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000,g/kg.bw/day
24,United States of America,2010,A000M,Amaranth grains,Children and Adolescents,6-14 years,male,1,0.003083,0.003083,...,0.000000,2155,2.090000e-07,0.0,0.0,0.0,0.0,0.0,0.000025,g/kg.bw/day
25,United States of America,2010,A000M,Amaranth grains,Adults and Elderly,15-49 years,male,4,0.001401,0.001429,...,0.000175,4415,1.160000e-06,0.0,0.0,0.0,0.0,0.0,0.000041,g/kg.bw/day

In [4]:
data1.FoodName.unique()

array(['Amaranth grains', 'Buckwheat', 'Common millet grain', ...,
       'Coconut milk powder', 'Juice concentrate, apple',
       'Juice concentrate, pineapple'], dtype=object)

In [6]:
# data2 = full list of FoodName 
data2 = data1.FoodName.unique()

In [7]:
len(data2)

1722

In [17]:
# data3 = data2 without Juice concentrate, apple
data3 = data2.drop(index='(Juice concentrate, apple)', inplace=True)

AttributeError: 'numpy.ndarray' object has no attribute 'drop'

In [18]:
# data frame = data from food_comsumption_US
data_US = pd.read_csv(r"C:\Users\dbsxsl\Desktop\Food_consumption_USA.csv") 
# Preview the first 5 lines of the loaded data 
data_US.head()

,Country,Year,FoodCode,FoodName,AgeClass,SourceAgeClass,Gender,Number_of_consumers,Consumers_Mean,Consumers_Median,...,Consumers_Standard_deviation__g_day_,Number_of_subjects,Total_Mean,Total_Median,Total_P05__g_day_,Total_P90__g_day_,Total_P95__g_day_,Total_P975__g_day_,Total_Standard_deviation__g_day_,Intake_Unit
0,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),All,All,All,21206,2.399773,1.222423,...,3.648792,24673,2.062562,0.877660,0.0,5.342004,8.516912,12.469750,3.484013,g/kg.bw/day
1,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),Infants and Toddlers,0-35 months,male,1055,7.332808,5.784557,...,6.721374,1379,5.609944,3.456111,0.0,14.530529,18.508600,22.245721,6.650332,g/kg.bw/day
2,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),Children and Adolescents,3-5 years,male,696,5.572249,3.964429,...,5.504145,734,5.283767,3.561653,0.0,13.149667,16.917949,19.955200,5.500126,g/kg.bw/day
3,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),Children and Adolescents,6-14 years,male,1950,2.378676,1.440215,...,3.060796,2155,2.152399,1.151835,0.0,5.593821,7.876653,10.422104,2.994015,g/kg.bw/day
4,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),Adults and Elderly,15-49 years,male,3489,1.141106,0.652453,...,1.535885,4415,0.901771,0.225668,0.0,2.593681,3.625575,4.669816,1.442200,g/kg.bw/day

In [19]:
# data1 = oringal data dataframe without NaN value  
data_US_1 = data_US.dropna() 
data_US_1.head()

,Country,Year,FoodCode,FoodName,AgeClass,SourceAgeClass,Gender,Number_of_consumers,Consumers_Mean,Consumers_Median,...,Consumers_Standard_deviation__g_day_,Number_of_subjects,Total_Mean,Total_Median,Total_P05__g_day_,Total_P90__g_day_,Total_P95__g_day_,Total_P975__g_day_,Total_Standard_deviation__g_day_,Intake_Unit
0,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),All,All,All,21206,2.399773,1.222423,...,3.648792,24673,2.062562,0.877660,0.0,5.342004,8.516912,12.469750,3.484013,g/kg.bw/day
1,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),Infants and Toddlers,0-35 months,male,1055,7.332808,5.784557,...,6.721374,1379,5.609944,3.456111,0.0,14.530529,18.508600,22.245721,6.650332,g/kg.bw/day
2,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),Children and Adolescents,3-5 years,male,696,5.572249,3.964429,...,5.504145,734,5.283767,3.561653,0.0,13.149667,16.917949,19.955200,5.500126,g/kg.bw/day
3,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),Children and Adolescents,6-14 years,male,1950,2.378676,1.440215,...,3.060796,2155,2.152399,1.151835,0.0,5.593821,7.876653,10.422104,2.994015,g/kg.bw/day
4,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),Adults and Elderly,15-49 years,male,3489,1.141106,0.652453,...,1.535885,4415,0.901771,0.225668,0.0,2.593681,3.625575,4.669816,1.442200,g/kg.bw/day

In [20]:
#identfy unique food names
uniquefood_US = data_US['FoodName'].unique()
print(uniquefood_US)

['(All Fruits)' '(All Nuts)' '(All Vegetables)' 'Alfalfa sprouts'
 'Algae and prokaryotes organisms' 'Almonds' 'Amaranth grains'
 'Aromatic herbs' 'Asparagus' 'Avocados' 'Bamboo shoots'
 'Barley grain, pearled' 'Basil' 'Beans (dry) and similar-' 'Beetroots'
 'Black eyed peas (dry)' 'Blond psyllium (infusion seeds, husks)'
 'Bovine liver' 'Bovine meat, dried' 'Brazil nuts' 'Broad beans (dry)'
 'Broccoli' 'Brussels sprouts' 'Buckwheat' 'Buffalo fresh meat'
 'Burdock, greater or edible' 'Butternut squashes' 'Carobs' 'Carrots'
 'Cashew nuts' 'Cassava roots' 'Cattle fresh fat tissue' 'Cauliflowers'
 'Cavendishes' 'Celeries' 'Cereal and cereal-like flours' 'Chards'
 'Chayote fruits' 'Chestnuts' 'Chicken fresh meat' 'Chickpeas (dry)'
 'Chicory roots' 'Chinese broccoli' 'Chinese cabbages'
 'Chinese water chestnut' 'Chives' 'Cinnamon bark' 'Citrons'
 'Citrus fruits' 'Coconuts' 'Collards' 'Common millet grain'
 'Common wheat grain' 'Coriander leaves' 'Cotton seed oil, edible'
 'Crustaceans' 'Cucumbers' 'Daikon' 'Dairy fats' 'Dandelions'
 'Dasheen taros' 'Dates' 'Dill leaves' 'Egg white' 'Egg yolk' 'Escaroles'
 'French beans (with pods)' 'Freshwater fish' 'Fungi'
 'Garden cress sprouts' 'Garden peas (dry)' 'Garlic' 'Ginger roots'
 'Globe artichokes' 'Goat muscle' 'Green onions' 'Guar beans (dry)'
 'Guavas' 'Hazelnuts' 'Head cabbages' 'Head lettuces' 'Honey' 'Hops'
 'Horseradish roots' 'Huckleberries' 'Indian mustards' 'Indian rice grain'
 'Jerusalem artichokes' 'Kales and similar-' 'Kidney bean (dry seeds)'
 'Leeks' 'Lentils (dry)' 'Lettuces' 'Lima beans (dry)' 'Linseed oil'
 'Linseeds' 'Litchis' 'Macadamias' 'Maize flour' 'Mammals and birds meat'
 'Mandarins and similar-' 'Maples (trunk sap)' 'Marine fish'
 'Marjoram, dry' 'Molluscs' 'Mung beans (dry)' 'Navy beans (dry seeds)'
 'Oat flour' 'Okra' 'Onions' 'Palm hearts' 'Palm oil/fat' 'Parsley'
 'Parsnip roots' 'Peanuts' 'Peas (with pods) and similar-' 'Pecans'
 'Peppermint' 'Pig muscle' 'Pigeon peas (dry)' 'Pine nut kernels'
 'Pistachios' 'Plantains' 'Pollen (residues of vegetal pollens)'
 'Potatoes' 'Poultry fresh meat (muscle meat)' 'Pumpkins'
 'Rabbit fresh meat' 'Radicchio' 'Radishes' 'Rape seed oil, edible'
 'Rhubarbs' 'Rice grain' 'Roman rocket' 'Rye grain' 'Shallots'
 'Sheep muscle' 'Soya proteins' 'Spinaches' 'Summer squashes'
 'Sunflower seeds' 'Swedes' 'Sweet corn' 'Sweet peppers' 'Sweet potatoes'
 'Table olives' 'Tomatillos' 'Tomatoes' 'Tuna' 'Turkey fresh meat'
 'Turmeric roots' 'Turnips' 'Walnuts' 'Watercresses' 'Wheat flour'
 'Whole eggs' 'Winter squashes' 'Witloofs' 'Yams']

In [21]:
#Identify number of uniqe food names in the data
n = len(data_US['FoodName'].unique())
  
print("No.of.unique values :", 
      n)

No.of.unique values : 159

In [23]:
#identfy unique AgeClass
uniqueAgeClass = data_US['AgeClass'].unique()
print(uniqueAgeClass)

['All' 'Infants and Toddlers' 'Children and Adolescents'
 'Adults and Elderly']

In [26]:
# Create All_Age dataframe from All age group in data_US data frame 
All_Age = data_US_1.loc[data['AgeClass'] == 'All', ['Country', 'Year', 'FoodCode', 'FoodName', 'SourceAgeClass', 'Gender', 'Number_of_consumers', 'Consumers_Mean', 'Consumers_Median', 'Number_of_subjects', 'Total_Mean', 'Total_Median', 'Intake_Unit']]

In [27]:
All_Age.head()

,Country,Year,FoodCode,FoodName,SourceAgeClass,Gender,Number_of_consumers,Consumers_Mean,Consumers_Median,Number_of_subjects,Total_Mean,Total_Median,Intake_Unit
0,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),All,All,21206,2.399773,1.222423,24673,2.062562,0.877660,g/kg.bw/day
13,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),All,male,10142,2.418906,1.150278,12061,2.034039,0.770229,g/kg.bw/day
14,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),All,female,11064,2.382236,1.279862,12612,2.089839,0.994380,g/kg.bw/day
21,United States of America,2010,eb31155c944a8c91ec4a53503cf50264,(All Nuts),All,All,12932,0.225916,0.081109,24673,0.118411,0.000011,g/kg.bw/day
34,United States of America,2010,eb31155c944a8c91ec4a53503cf50264,(All Nuts),All,male,6084,0.249923,0.091060,12061,0.126070,0.000004,g/kg.bw/day

In [28]:
# Create Infants_Toddlers dataframe from All age group in data_US data frame 
Infants_Toddlers = data_US_1.loc[data['AgeClass'] == 'Infants and Toddlers', ['Country', 'Year', 'FoodCode', 'FoodName', 'SourceAgeClass', 'Gender', 'Number_of_consumers', 'Consumers_Mean', 'Consumers_Median', 'Number_of_subjects', 'Total_Mean', 'Total_Median', 'Intake_Unit']]
Infants_Toddlers.head()

,Country,Year,FoodCode,FoodName,SourceAgeClass,Gender,Number_of_consumers,Consumers_Mean,Consumers_Median,Number_of_subjects,Total_Mean,Total_Median,Intake_Unit
1,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),0-35 months,male,1055,7.332808,5.784557,1379,5.609944,3.456111,g/kg.bw/day
7,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),0-35 months,female,998,7.336989,5.724693,1290,5.676213,3.618839,g/kg.bw/day
15,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),0-35 months,All,2053,7.334840,5.746264,2669,5.641973,3.550847,g/kg.bw/day
22,United States of America,2010,eb31155c944a8c91ec4a53503cf50264,(All Nuts),0-35 months,male,458,0.397070,0.174714,1379,0.131877,0.000000,g/kg.bw/day
28,United States of America,2010,eb31155c944a8c91ec4a53503cf50264,(All Nuts),0-35 months,female,383,0.361872,0.108571,1290,0.107439,0.000000,g/kg.bw/day

In [29]:
# Create Children_Adolescents dataframe from All age group in data_US data frame 
Children_Adolescents = data_US_1.loc[data['AgeClass'] == 'Children and Adolescents', ['Country', 'Year', 'FoodCode', 'FoodName', 'SourceAgeClass', 'Gender', 'Number_of_consumers', 'Consumers_Mean', 'Consumers_Median', 'Number_of_subjects', 'Total_Mean', 'Total_Median', 'Intake_Unit']]
Children_Adolescents.head()

,Country,Year,FoodCode,FoodName,SourceAgeClass,Gender,Number_of_consumers,Consumers_Mean,Consumers_Median,Number_of_subjects,Total_Mean,Total_Median,Intake_Unit
2,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),3-5 years,male,696,5.572249,3.964429,734,5.283767,3.561653,g/kg.bw/day
3,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),6-14 years,male,1950,2.378676,1.440215,2155,2.152399,1.151835,g/kg.bw/day
8,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),3-5 years,female,649,5.373984,3.801211,684,5.098999,3.559325,g/kg.bw/day
9,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),6-14 years,female,1976,2.375592,1.498022,2175,2.158239,1.285138,g/kg.bw/day
16,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),3-5 years,All,1345,5.476580,3.904059,1418,5.194641,3.561387,g/kg.bw/day

In [30]:
# Create Adults_Elderly dataframe from All age group in data_US data frame 
Adults_Elderly = data_US_1.loc[data['AgeClass'] == 'Adults and Elderly', ['Country', 'Year', 'FoodCode', 'FoodName', 'SourceAgeClass', 'Gender', 'Number_of_consumers', 'Consumers_Mean', 'Consumers_Median', 'Number_of_subjects', 'Total_Mean', 'Total_Median', 'Intake_Unit']]
Adults_Elderly.head()

,Country,Year,FoodCode,FoodName,SourceAgeClass,Gender,Number_of_consumers,Consumers_Mean,Consumers_Median,Number_of_subjects,Total_Mean,Total_Median,Intake_Unit
4,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),15-49 years,male,3489,1.141106,0.652453,4415,0.901771,0.225668,g/kg.bw/day
5,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),50-74 years,male,2217,1.421657,0.957320,2581,1.221159,0.738099,g/kg.bw/day
6,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),>75 years,male,735,1.559994,1.215246,797,1.438639,1.027299,g/kg.bw/day
10,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),15-49 years,female,4268,1.298593,0.782445,5031,1.101649,0.483369,g/kg.bw/day
11,United States of America,2010,e0248419de35acf267cbd31e1f7cac29,(All Fruits),50-74 years,female,2413,1.628660,1.218268,2634,1.492010,1.067458,g/kg.bw/day